In [2]:
from sklearn.datasets import load_iris

In [4]:
import pandas as pd 
import numpy as np 

In [6]:
iris=load_iris()

In [8]:
from sklearn.linear_model import LogisticRegression

In [10]:
li=LogisticRegression()

In [12]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [34]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

In [38]:
li.fit(x_train,y_train)
li.score(x_test,y_test)

0.9555555555555556

In [40]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9555555555555556

In [42]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9555555555555556

In [52]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),iris.data,iris.target)


E:\pc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [54]:
cross_val_score(SVC(),iris.data,iris.target)


array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [56]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])